heat_template_version: 2016-04-08
description: Stack that launches a single server and installs APACHE

parameters:
  public_network:
    type: string
    default: Public Network
  net:
    type: string
    constraints:
      - custom_constraint: neutron.network
  image:
    type: string
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    constraints:
      - custom_constraint: nova.flavor
  ssh_keys:
    type: string
    default: centos
    #type: comma_delimited_list

resources:
 

  allow_ssh_http:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming SSH, HTTP and ICMP traffic from anywhere.
      name: 
        list_join: [ '-', [ { get_param: "OS::stack_name" }, 'kickstart', 'allow incoming traffic, tcp port 22, 80 and icmp']]
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 80, port_range_max: 80, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp } 

  port:
    type: OS::Neutron::Port
    depends_on: [ allow_ssh_http ]
    properties:
      network: { get_param: net }
      security_groups: [ get_resource: allow_ssh_http ]

  floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: [ port ]
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_resource: port }

  apache_server:
      type: OS::Nova::Server
      properties:
          name: openshift-AIO
          image: { get_param: image } 
          flavor: { get_param: flavor }
          networks:
              - port: { get_resource: port }
          user_data_format: RAW
          key_name: { get_param: ssh_keys }
          user_data: |
              #!/bin/bash
              echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
              echo "Begin: run user_data bash script. "
              apt-get update
              apt-get -y install apache2
              echo "127.0.0.1  `hostname`" >> /etc/hosts
              /etc/init.d/apache2 restart
              echo "End: run user_data bash script. "
              echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
      
outputs:

    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [apache_server, first_address] }

    website_url:
        description: URL for Openshift URL
        value: 
            list_join: ['', ['http://', get_attr: [apache_server, first_address], '/openshift']]
